/**
 * InstallManifest - AI-generated installation blueprint
 * The intermediate JSON structure before converting to Pinokio Script
 * Generated by AIController based on natural language input
 */

class InstallManifest {
  /**
   * Create a new InstallManifest
   * @param {Object} data - Manifest data
   */
  constructor(data = {}) {
    this.appName = data.appName || '';
    this.sourceUrl = data.sourceUrl || '';
    this.detectedType = data.detectedType || 'unknown'; // python, node, rust, docker, unknown
    this.requirements = Array.isArray(data.requirements) ? data.requirements : [];
    this.installCommands = Array.isArray(data.installCommands) ? data.installCommands : [];
    this.runCommand = data.runCommand || '';
    this.envVars = data.envVars || {};
    this.models = Array.isArray(data.models) ? data.models : [];
    this.metadata = data.metadata || {};
  }

  /**
   * Validate the manifest
   * @returns {Object} Validation result { valid: boolean, errors: string[] }
   */
  validate() {
    const errors = [];

    // Required fields
    if (!this.appName || this.appName.trim() === '') {
      errors.push('appName is required');
    }

    if (!this.sourceUrl || this.sourceUrl.trim() === '') {
      errors.push('sourceUrl is required');
    }

    // Validate source URL format
    if (this.sourceUrl) {
      try {
        new URL(this.sourceUrl);
      } catch (e) {
        errors.push(`Invalid sourceUrl: ${this.sourceUrl}`);
      }
    }

    // Validate detected type
    const validTypes = ['python', 'node', 'rust', 'docker', 'unknown'];
    if (!validTypes.includes(this.detectedType)) {
      errors.push(`Invalid detectedType: ${this.detectedType}. Must be one of: ${validTypes.join(', ')}`);
    }

    // Validate install commands are strings
    if (this.installCommands.length > 0) {
      const invalidCommands = this.installCommands.filter(cmd => typeof cmd !== 'string');
      if (invalidCommands.length > 0) {
        errors.push('All installCommands must be strings');
      }
    }

    // Validate run command
    if (this.runCommand && typeof this.runCommand !== 'string') {
      errors.push('runCommand must be a string');
    }

    // Validate env vars
    if (this.envVars && typeof this.envVars !== 'object') {
      errors.push('envVars must be an object');
    }

    // Validate models
    if (this.models.length > 0) {
      this.models.forEach((model, index) => {
        if (!model.url) {
          errors.push(`Model at index ${index} missing required field: url`);
        }
        if (!model.path) {
          errors.push(`Model at index ${index} missing required field: path`);
        }

        // Validate URL format
        if (model.url) {
          try {
            new URL(model.url);
          } catch (e) {
            errors.push(`Invalid model URL at index ${index}: ${model.url}`);
          }
        }
      });
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  /**
   * Check for dangerous commands
   * @returns {Object} Safety check result { safe: boolean, warnings: string[] }
   */
  checkSafety() {
    const warnings = [];

    // Dangerous command patterns
    const dangerousPatterns = [
      { pattern: /rm\s+-rf\s+\//, message: 'Dangerous: rm -rf / detected' },
      { pattern: /:\(\)\{.*;\};/, message: 'Dangerous: Fork bomb detected' },
      { pattern: /mkfs/, message: 'Dangerous: Filesystem format command detected' },
      { pattern: /dd\s+if=.*of=\/dev/, message: 'Dangerous: Disk write command detected' },
      { pattern: />\/dev\/sda/, message: 'Dangerous: Writing to disk device' },
      { pattern: /curl.*\|\s*bash/, message: 'Warning: Piping curl to bash (security risk)' },
      { pattern: /wget.*\|\s*sh/, message: 'Warning: Piping wget to sh (security risk)' },
      { pattern: /sudo\s+chmod\s+777/, message: 'Warning: chmod 777 with sudo (insecure)' }
    ];

    // Check install commands
    this.installCommands.forEach((cmd, index) => {
      dangerousPatterns.forEach(({ pattern, message }) => {
        if (pattern.test(cmd)) {
          warnings.push(`Install command ${index}: ${message}`);
        }
      });
    });

    // Check run command
    if (this.runCommand) {
      dangerousPatterns.forEach(({ pattern, message }) => {
        if (pattern.test(this.runCommand)) {
          warnings.push(`Run command: ${message}`);
        }
      });
    }

    return {
      safe: warnings.length === 0,
      warnings
    };
  }

  /**
   * Convert to Pinokio script format with GAS-awareness
   * @param {boolean} useGas - Generate GAS-aware download commands (default: true)
   * @returns {Object} Pinokio script JSON
   */
  toPinokioScript(useGas = true) {
    const script = {
      daemon: true,
      run: [
        // Clone repository
        {
          method: "shell.run",
          params: {
            message: `Cloning ${this.appName}...`,
            path: "{{kernel.path('api')}}",
            venv: "env",
            conda: this.detectedType === 'python' ? 'true' : undefined
          }
        }
      ]
    };

    // Add git clone
    script.run[0].params.message = [`git clone ${this.sourceUrl} ${this.appName}`];

    // Add install commands
    if (this.installCommands.length > 0) {
      script.run.push({
        method: "shell.run",
        params: {
          message: this.installCommands,
          path: `{{kernel.path('api/${this.appName}')}}`,
          venv: "env",
          conda: this.detectedType === 'python' ? 'true' : undefined
        }
      });
    }

    // Add model downloads if any
    if (this.models.length > 0) {
      if (useGas) {
        // Add GAS-aware download section
        script.run.push({
          method: "notify",
          params: {
            html: `📦 <b>Downloading models via GAS</b><br>Models will be deduplicated and shared across apps`
          }
        });
      }

      this.models.forEach(model => {
        if (useGas) {
          // GAS-aware download: uses fs.download but with understanding that
          // future pinokiod integration will intercept and use GAS
          script.run.push({
            method: "fs.download",
            params: {
              url: model.url,
              path: `{{kernel.path('api/${this.appName}/${model.path}')}}`,
              // Note: In GAS-integrated pinokiod, this will:
              // 1. Check if model exists in GAS (by URL)
              // 2. If exists: symlink from GAS to target path
              // 3. If not: download to GAS, then symlink to target path
              _gas_hint: {
                enabled: true,
                description: model.description || 'Model file'
              }
            }
          });
        } else {
          // Legacy download (direct to app folder)
          script.run.push({
            method: "fs.download",
            params: {
              url: model.url,
              path: `{{kernel.path('api/${this.appName}/${model.path}')}}`
            }
          });
        }
      });
    }

    // Add run command
    if (this.runCommand) {
      script.run.push({
        method: "shell.run",
        params: {
          message: this.runCommand,
          path: `{{kernel.path('api/${this.appName}')}}`,
          venv: "env",
          conda: this.detectedType === 'python' ? 'true' : undefined,
          env: this.envVars
        }
      });
    }

    return script;
  }

  /**
   * Convert to JSON string
   * @param {boolean} pretty - Pretty print
   * @returns {string} JSON string
   */
  toJSON(pretty = false) {
    return JSON.stringify({
      appName: this.appName,
      sourceUrl: this.sourceUrl,
      detectedType: this.detectedType,
      requirements: this.requirements,
      installCommands: this.installCommands,
      runCommand: this.runCommand,
      envVars: this.envVars,
      models: this.models,
      metadata: this.metadata
    }, null, pretty ? 2 : 0);
  }

  /**
   * Create from JSON string
   * @param {string} json - JSON string
   * @returns {InstallManifest} Manifest instance
   */
  static fromJSON(json) {
    try {
      const data = JSON.parse(json);
      return new InstallManifest(data);
    } catch (error) {
      throw new Error(`Failed to parse JSON: ${error.message}`);
    }
  }

  /**
   * Get summary for display
   * @returns {Object} Summary
   */
  getSummary() {
    return {
      name: this.appName,
      source: this.sourceUrl,
      type: this.detectedType,
      commandCount: this.installCommands.length,
      modelCount: this.models.length,
      hasRunCommand: !!this.runCommand
    };
  }
}

module.exports = InstallManifest;
